version: "3.7"
services:
    pkg:
        build: .
        ports:
            - "5002:5002"
        depends_on:
            - game_db
    game_db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
          - game_volume:/var/opt/mssql

        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433"
            - "1002:1433"
volumes:
  game_volume: