// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoBHo_GameEngine.Contexts;

namespace RoBHo_GameEngine.Migrations
{
    [DbContext(typeof(GameEngineContext))]
    partial class GameEngineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RoBHo_GameEngine.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterClass")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("RoBHo_GameEngine.Models.CharacterLvl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId1")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId2")
                        .HasColumnType("int");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("int");

                    b.Property<int>("Lvl")
                        .HasColumnType("int");

                    b.Property<int>("LvlType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("CharacterId1")
                        .IsUnique()
                        .HasFilter("[CharacterId1] IS NOT NULL");

                    b.HasIndex("CharacterId2")
                        .IsUnique()
                        .HasFilter("[CharacterId2] IS NOT NULL");

                    b.ToTable("CharacterLvls");
                });

            modelBuilder.Entity("RoBHo_GameEngine.Models.CharacterLvl", b =>
                {
                    b.HasOne("RoBHo_GameEngine.Models.Character", "Character")
                        .WithOne("Combatlvl")
                        .HasForeignKey("RoBHo_GameEngine.Models.CharacterLvl", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoBHo_GameEngine.Models.Character", null)
                        .WithOne("CraftingLvl")
                        .HasForeignKey("RoBHo_GameEngine.Models.CharacterLvl", "CharacterId1");

                    b.HasOne("RoBHo_GameEngine.Models.Character", null)
                        .WithOne("GatheringLvl")
                        .HasForeignKey("RoBHo_GameEngine.Models.CharacterLvl", "CharacterId2");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RoBHo_GameEngine.Models.Character", b =>
                {
                    b.Navigation("Combatlvl");

                    b.Navigation("CraftingLvl");

                    b.Navigation("GatheringLvl");
                });
#pragma warning restore 612, 618
        }
    }
}
